# version
__version__ = "1.0.4"

# python
import os
import sys
import logging
import shutil

# cytomine
import cytomine
from cytomine.models.annotation import Annotation, AnnotationCollection
from cytomine.models.image import ImageInstance
from cytomine.models.software import Job, JobCollection, JobData, JobDataCollection
from cytomine.models.user import UserJob, UserJobCollection


# ------------------------------ Support functions ------------------------------

# Función que recoge las coordenadas de todas las anotaciones manuales
def get_anotaciones_general(params):
    general_annots = AnnotationCollection()
    general_annots.project = params.cytomine_id_project
    general_annots.image = params.image_to_analyze
    
    general_annots.showWKT = True
    general_annots.showMeta = True
    general_annots.showGIS = True
    general_annots.showTerm = True
    
    general_annots.fetch()
    
    manual_annots = []
    
    for general_annot in general_annots:
        if general_annot.term == []:
            manual_annots.append(general_annot)

    User_list = []
    Area_list = []
    Perimeter_list = []
    WKT_list = []
    
    for manual_annot in manual_annots:
            User_list.append(manual_annot.user)
            Area_list.append(manual_annot.area)
            Perimeter_list.append(manual_annot.perimeter)
            WKT_list.append(manual_annot.location)
            
        dict = {"User":User_list,
                "Area":Area_list,
                "Perimeter":Perimeter_list,
                "Geometría":WKT_list}
        
    return dict

# ------------------------------ Step functions ------------------------------

# STEP 1: buscar parches
###def get_parches(params):
    ###diccionario = get_anotaciones_general(params)
    ###if diccionario["Perimeter"] == 4096

# STEP 2: recuperar detecciones de dentro del parche


# STEP 3: buscar anotaciones manuales dentro del parche

# ------------------------------ Main function ------------------------------
def run(cyto_job, parameters):
    logging.info("----- test software v%s -----", __version__)
    logging.info("Entering run(cyto_job=%s, parameters=%s)", cyto_job, parameters)

    job = cyto_job.job
    project = cyto_job.project

    # I create a working directory that I will delete at the end of this run
    working_path = os.path.join("tmp", str(job.id))
    if not os.path.exists(working_path):
        logging.info("Creating working directory: %s", working_path)
        os.makedirs(working_path)

    try:
        # STEP 0: anotaciones en general (para visualizar el diccionario)
        diccionario = anotaciones_general(parameters)
        # STEP 1: parches
        
        # STEP 2: detecciones
        
        # STEP 3: anotaciones manuales
         
        
        output_path = os.path.join(working_path, "output.txt")
        f= open(output_path,"w+")
        f.write(diccionario)
        f.close()

        #I save a file generated by this run into a "job data" that will be available in the UI. 
        job_data = JobData(job.id, "Generated File", "output.txt").save()
        job_data.upload(output_path)

    finally:
        logging.info("Deleting folder %s", working_path)
        shutil.rmtree(working_path, ignore_errors=True)
        logging.debug("Leaving run()")


if __name__ == "__main__":
    logging.debug("Command: %s", sys.argv)

    with cytomine.CytomineJob.from_cli(sys.argv) as cyto_job:
        run(cyto_job, cyto_job.parameters)


